worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream app_servers {
        server app:80;
    }

    # Preservar X-Forwarded-Proto original de Ngrok/CloudFlare si existe, o usar $scheme como fallback
    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        ""      $scheme;
    }

    server {
        listen 80;
        server_name _;

        client_max_body_size 10M;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_buffering off;
        }
    }
}
